<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>master Store</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0f0b2240-f07e-4370-813b-8e7aaa590a24</testSuiteGuid>
   <testCaseLink>
      <guid>838f28c5-9442-4a0a-a39e-b17c4b229cad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login mascot/login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baaa1c4f-994a-4465-8b42-c0d12af1ba61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c605e78-12bb-48d8-a3f3-049648024026</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81beb003-6ab3-472d-8832-518d3a326c0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User Management - Master Store/Open Master Store</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1e2847ea-b75f-4865-a174-1dd7c8c4c86f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Driven/Data Driven - Open Master Store</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1e2847ea-b75f-4865-a174-1dd7c8c4c86f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>32b27b93-7df5-4623-8d16-87d2397e8383</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1e2847ea-b75f-4865-a174-1dd7c8c4c86f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>7ac77dfc-f1cc-4591-9e95-b38ba446983e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
